name:                bookhound
version:             0.1.0
github:              "albertprz/bookhound"
license:             LGPL
author:              "Alberto Perez Lopez"
maintainer:          "albertoperez1994@gmail.com"
copyright:           "2021 Alberto Perez Lopez"

extra-source-files:
- README.md

# Metadata used when publishing your package
synopsis:            Simple Parser Combinators & Parsers for usual data formats
category:            Parsers

# To avoid duplicated efforts in documentation and dealing with the
# complications of embedding Haddock markup inside cabal files, it is
# common to point users to the README.md file.
description: Please see the README on GitHub at <https://github.com/albertprz/bookhound#readme>

dependencies:
- base >= 4.7 && < 5
- containers >= 0.6 && < 1
- time >= 1.9 && < 2
- split >= 0.1.2 && < 0.2

library:
  source-dirs: src
