name:                bookhound
version:             0.1.26.0
github:              "albertprz/bookhound"
license:             LGPL
author:              "Alberto Perez Lopez"
maintainer:          "albertoperez1994@gmail.com"
copyright:           "2021 Alberto Perez Lopez"

extra-source-files:
- README.md

# Metadata used when publishing your package
synopsis:            Simple Parser Combinators
category:            Parser Combinators

# To avoid duplicated efforts in documentation and dealing with the
# complications of embedding Haddock markup inside cabal files, it is
# common to point users to the README.md file.
description: Please see the README on GitHub at <https://github.com/albertprz/bookhound#readme>

dependencies:
- base >= 4 && < 5
- text >= 2.0 && < 3
- containers  >= 0.6 && < 0.7
- mtl >= 2 && < 3
- time >= 1 && < 2

ghc-options:
- -Wall
- -Wcompat
- -Widentities
- -Wincomplete-record-updates
- -Wpartial-fields
- -Wincomplete-uni-patterns
- -Wredundant-constraints

default-extensions:
# Syntax
- LambdaCase
- MultiWayIf
- TupleSections
- BlockArguments
- PostfixOperators

# Types
- RankNTypes
- ScopedTypeVariables

# Records
- DuplicateRecordFields
- NamedFieldPuns
- RecordWildCards

# Type Classes
- MultiParamTypeClasses
- FlexibleInstances

# Convenience
- ApplicativeDo
- OverloadedStrings

library:
  source-dirs: src

tests:
  test:
    build-tools: hspec-discover
    source-dirs: test
    main: Spec.hs
    dependencies:
    - hspec
    - QuickCheck
    - bookhound
    - quickcheck-instances
    ghc-options:
    - -Wno-type-defaults
